### ISSUE TITLE
Todo list for future development

### ISSUE THREAD

**Issue by Nats-ji** [WolvenKit/BraindanceProtocol#94]
- [x] Add a favorite button for adding protocols to the favorites list 
- [x] Add a button for adding any protocols to the hotkey list
- [ ]  Scale UI with font size
